environment:

  matrix:
    - nodejs_version: "11"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --ignore-engines

test_script:
  - npx jest

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

build: off
deploy: off
